spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
          zkNodes: localhost:2181
          replicationFactor: 3
      bindings:
        topic_in:
          destination: test4
          group: group
          consumer:
            maxAttempts: 1
            partitioned: true
server:
  port: 0
